## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  
julia:
  - nightly
  - 1.2
  - 1.0

notifications:
  email: true

matrix:
  allow_failures:
  - julia: nightly
  
codecov: true
coveralls: true

after_success:
- julia --project=coverage/ -e 'using Pkg; Pkg.instantiate();
   			        using Coverage; Codecov.submit(Codecov.process_folder())';
				
- julia --project=coverage/ -e 'using Pkg; Pkg.instantiate();
   			        using Coverage; Coveralls.submit(process_folder())';

jobs:
  include:
    - stage: "Documentation"
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      name: "HTML"
      after_success: skip
