## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx
  - windows
	
julia:
  - nightly
  - 1.1
  - 1.0
  
notifications:
  email: false

git:
  depth: 99999999

codecov: true
coveralls: true

