## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  
julia:
  - nightly
  - 1.1.1
  - 1.0.4
  
notifications:
  email: true
  
git:
  depth: 99999999
  
codecov: true
coveralls: true

after_success:
  push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("msJ")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("msJ")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'