## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx
  - os: windows
	
julia:
  - nightly
  - 1.1
  - 1.0
  
notifications:
  email: false
    
codecov: true
coveralls: true
