## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx
  
julia:
  - nightly
  - 1.1
  - 1.0
  
notifications:
  email: false

git:
  depth: 99999999

codecov: true
coveralls: true

after_success:
- julia -e 'using Pkg; cd(Pkg.dir("msJ")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
- julia -e 'using Pkg; cd(Pkg.dir("msJ")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'